[package]
name = "promformat"
author = "vmalloc"
version = "0.1.0"
edition = "2021"
license = "Apache"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
